### ISSUE TITLE
Remove some unnecessary domains from the DAP section

### ISSUE THREAD

**Issue by tdlowden** [18F/pulse#185]
https://pulse.cio.gov/analytics/domains/#q=U.%20S.%20Peace%20Corps

peacecore.gov and peacecorp.gov are not technically redirects, but they are dead sites. I'll see if I can find others in similar vein.

**Comment by konklone** [comment]
I'd rather have the Peace Corps update their domains to be proper redirects, since they're clearly not being used for anything else. Can you try pinging them first before we start adding in exceptions?

**Comment by tdlowden** [comment]
Good idea. Does anyone in your office have a good contact? I only know the past webmaster who recently left.

**Comment by cmc333333** [comment]
I don't understand the problem, but @sshami is probably your guy.

**Comment by tdlowden** [comment]
Thanks @cmc333333! @sshami, any reason peacecore.gov & peacecorp.gov don't redirect to the proper site?

**Comment by sshami** [comment]
@tdlowden Thanks, we are aware of this issue and I've contacted our technical POC for .GOV DNS registration. Realistically, I'm not sure when we'll get this resolved, but I'll keep you updated.

**Comment by tdlowden** [comment]
appreciate the timely response @sshami :)

**Comment by sshami** [comment]
@tdlowden peacecore.gov & peacecorp.gov redirect has been fixed.

**Comment by konklone** [comment]
@sshami Almost! The root domains redirect successfully, but `http://www.peacecorp.gov` still loads a plain nginx page, and so our scanners will not pick up `peacecorp.gov` as a "redirector". You should update or remove the DNS record for `www.peacecorp.gov` so that our systems will exclude it from checking for DAP.

`http://www.peacecore.gov` doesn't return anything, and so our scanner won't factor it in, and `peacecore.gov` _will_ come up as a "redirector". That domain is fine.

Also, @sshami, to be clear, this will fix it for DAP, but `peacecorp.gov` and `peacecore.gov` are still on the hook to implement HTTPS, even just for the purposes of redirecting. Thank you for your help!

**Comment by gbinal** [comment]
This appears to be [addressed](https://pulse.cio.gov/analytics/domains/#q=U.%20S.%20Peace%20Corps).  I'm going to go ahead and close the issue.
