### ISSUE TITLE
Healthcare.gov - HSTS w/ Preload

### ISSUE THREAD

**Issue by gellerb** [18F/pulse#202]
According to Pulse, Healthcare.gov 'is not ready for preload' but if one looks at the response headers the preload flag is present and the domain is also included in Chromium's HSTS Preload list[1]. The idea of 'is domain preload ready' is great b/c it allows one to gauge how many domains could be added to Chromium's HSTS Preload list once the HSTS header is added with ‘includeSubDomains’. However, the Chromium team does make exceptions regarding the requirements. At the moment, Pulse incorrectly labels both Healthcare.gov and the Spanish site (Cuidadodesalud.gov)

[1] https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json#2254

**Comment by konklone** [comment]
@gellerb You're absolutely right, and this is something I'm familiar with. But this is also why we chose the term "preload-ready" and not "preloaded". Our goal here isn't (currently) to measure whether a domain is currently _in_ the HSTS preload list, because -- as you've observed -- that's a human process where exceptions are possible.

Our goal here is to measure whether a domain has achieved the maximum HTTPS coverage possible, and the HSTS preload list's requirements for a domain (long max-age, `includeSubDomains` on root) is an excellent way to measure that.

I personally don't think marking healthcare.gov as "preload-ready" would be appropriate, because `healthcare.gov` has not established the same level of protection as `aids.gov` or `acus.gov`. Subdomains of `healthcare.gov` are not protected by HSTS, so to give `healthcare.gov` an evaluation in our table that suggests otherwise would not be accurate.

Fundamentally, an automated evaluation like ours will always have edge cases, and this is one of them. I'd prefer to stick with a methodology that motivates domains to "finish the job" and protect all of their subdomains, in order to get the best marking. "Preload-ready" is an imperfect, but really pretty good, way of doing that. We could hardcode in some exceptions for `healthcare.gov` that mark it in some in-between way that captures all the nuances, but hardcoding in exceptions has its own downsides.

In any case, thank you for filing this, and I'll make sure the healthcare.gov team sees the discussion.
