### ISSUE TITLE
Help Request: pulse.hhs.gov

### ISSUE THREAD

**Issue by shallbetter** [18F/pulse#214]
Looking to stand up a webserver to host an HHS-specific instance so we can report against our sub-organizations, longer list of sub-domains, and try to help add some more technical dashboards to the mix.  

We would be standing this up on our own virtual environment not AWS.  Can you help scope the server-side needs beyond the basic:

* Linux
* Apache
* MySQL
* PHP
* Python

**Comment by konklone** [comment]
The website itself is all static files, and the data pipeline is some Python and other CLI tools that output to STDOUT and disk. So you wouldn't need PHP or MySQL for anything. You can host static files with tons of things -- nginx and Apache both make good sense (we use nginx for just about everything).

Because the website is static files, and the data it ends up consuming is static, you could also host all of this in S3/CloudFront or GitHub Pages/Cloudflare or some other service optimized for static file hosting over HTTPS.

In either case, the first step is to build the site. You can try running this site with the data it's got currently versioned in it. You should be able to do that with the information in this project's README. 

The data pipeline work could be better documented, as in #105, but I'm happy to help you understand anything that's not clear. For HTTPS, it involves running https://github.com/18F/domain-scan with https://github.com/benbalter/site-inspector v1.0.2 (not v2) and the latest version of https://github.com/ssllabs/ssllabs-scan.

Any additional tech dashboards you make, both the data collection and the display aspect, we'd love to now about and incorporate here if feasible. Open source collaboration!

Also: I don't suppose we could convince you to publish your list of subdomains? We're looking to expand this to include them.

**Comment by shallbetter** [comment]
I'd be happy to share our list of URLs.  I'm positive it is not comprehensive, but it is a significant number more than you are listing (286).  I'd rather not see the full list published on pulse.cio.gov, but wouldn't mind having them tested.  This was really the intent of standing up an HHS version that I could show the same status but for sites associated by sub-organization (FDA, CDC, NIH, CMS, IHS, etc).

Is there someone with time to provide more direct assistance.  I have a basic unix webserver with ruby, python et al stood up in AWS, but it sure would be easier to simply take an image or have some more direct assistance.

**Comment by konklone** [comment]
Sure, if you want to email us the list of subdomains, we won't use that list to populate pulse.cio.gov, and will just use it for some direct testing. (Though we do have plans to expand pulse.cio.gov into subdomains more generally.)

> Is there someone with time to provide more direct assistance. I have a basic unix webserver with ruby, python et al stood up in AWS, but it sure would be easier to simply take an image or have some more direct assistance.

Are there specific things we could document that could make this easier? There is a Docker Compose file for `domain-scan`, though that may not be what you want. I don't know if we can promise extensive hands-on assistance, but if you're by the GSA DC HQ any time soon, feel free to drop by 18F and I can go through anything that's unclear (and channel that into docs).

**Comment by konklone** [comment]
Closing for a lack of activity, but happy to re-open if you want to discuss further.
