### ISSUE TITLE
Automatically keep data up to date

### ISSUE THREAD

**Issue by garrettr** [18F/pulse#237]
From the README, it appears that updating the data in Pulse is a manual affair. Every time you want to update the data, you need to *manually* run `./domain-scan`, then *manually* do everything in "Step 3" to update Pulse with the new results from the scan.`

Since the scan is totally automated, wouldn't it be better to have Pulse store its data in a database that is periodically and automatically updated? That way there is no need for a human to manually intervene to keep the data current. Additionally, it would enable a number of other features as well - for example, tracking changes over time (#216) would become trivial.

**Comment by konklone** [comment]
> Since the scan is totally automated, wouldn't it be better to have Pulse store its data in a database that is periodically and automatically updated? That way there is no need for a human to manually intervene to keep the data current.

While a database might be easier to automatically update than a git repo, the primary issue isn't really the lack of a database. We first need to set up the infrastructure: a server, with cron jobs or the like, with admin/error reporting

We also have more to go on automating the fetching the input data. Right now, the input data for the process are two CSVs that only update once a quarter, and a public scan of the internet. The public scan we can run nightly, now that we did some recent work in https://github.com/18F/domain-scan/pull/22 to parallelize the workflow and cut its time down (from 16 hours to 3). We're working to automate one of the two input CSVs (participating DAP sites) now. 

Automating the full scan process is likely to come, but not in the immediate term. When we do, I *suspect* it's likely to work similarly to how https://analytics.usa.gov works, where we persist the data by automatically uploading it to S3 and then loading it client-side through JS, rather than writing it to a database. The tables in Pulse here already load in data client-side through JS, so it's really just swapping out the location it's being pulled from.

I'll happily leave this open as a ticket to cover the milestone of achieving end-to-end automation, at least for DAP and HTTPS data (automating the official .gov domain list can be done separately).

**Comment by garrettr** [comment]
> Automating the full scan process is likely to come, but not in the immediate term. When we do, I suspect it's likely to work similarly to how https://analytics.usa.gov works, where we persist the data by automatically uploading it to S3 and then loading it client-side through JS, rather than writing it to a database. The tables in Pulse here already load in data client-side through JS, so it's really just swapping out the location it's being pulled from.

This sounds like a great approach to me. I'd be glad if you re-purposed this ticket to cover the milestone of achieving end-to-end automation, and will defer to you for the specifics of the approach.

**Comment by gbinal** [comment]
Closing this as the production scans have been updated to be automatic.
