### ISSUE TITLE
Add a content check to SSL test

### ISSUE THREAD

**Issue by johnvenable-nist** [18F/pulse#241]
I suggest when checking SSL you also check for valid 200 HTTP code. You can get an A on the test even though it returns a 404.

**Comment by konklone** [comment]
Hi @johnvenable-nist - you're right, but by our metrics, that situation is okay. We measure a site if it's reachable over HTTP, rather than discriminating based on response code. This is in part because website/.gov use of response codes isn't super accurate (people return 200 response codes for 404 pages all the time) and in part because a 404 page is still "publicly accessible", and for HTTPS/TLS we want to measure all publicly accessible sites/domains.

I'm closing, but happy to discuss more or talk about specific edge cases. Thanks for opening this!
