### ISSUE TITLE
Our scanning server doesn't have the latest roots

### ISSUE THREAD

**Issue by konklone** [18F/pulse#334]
We're failing to connect to https://edpubs.gov and https://fsapubs.gov because they use a cert that chains to `Entrust Root Certification Authority - G2`. This is a new (as of 2015) root:

https://bugzilla.mozilla.org/show_bug.cgi?id=849950

And is not in Ubuntu 14.04 (I updated the `ca-certificates` package and this didn't seem to change anything). However, it is in Ubuntu 15.10, and OS X.

I think the solution is to install a newer ca-certificates package on the server manually, as I believe it's our responsibility to make sure we're scanning from a server whose root store is as up to date as the browser userbase of the sites we're scanning.

**Comment by garrettr** [comment]
For detail, the relevant update to the `ca-certificates` package in precise/wily is [20150426](http://changelogs.ubuntu.com/changelogs/pool/main/c/ca-certificates/ca-certificates_20150426ubuntu1/changelog), while the package in trusty hasn't been updated since [20141019ubuntu0.14.04.1](http://changelogs.ubuntu.com/changelogs/pool/main/c/ca-certificates/ca-certificates_20141019ubuntu0.14.04.1/changelog).

Since 14.04 is LTS, shouldn't it be Ubuntu's responsibility to backport the updates to `ca-certificates`? I asked around on #ubuntu on Freenode but didn't get a response. It might be worth filing a Launchpad ticket for this.

**Comment by konklone** [comment]
> Since 14.04 is LTS, shouldn't it be Ubuntu's responsibility to backport the updates to ca-certificates?

I agree! But in the absence of that, I think we have to keep it up to date myself. 

Similarly, @agwa has been on Debian's case about keeping ca-certificates up to date on their end: https://bugs.debian.org/806239 I don't understand why it's like pulling teeth.

**Comment by konklone** [comment]
Also - I did update our server with the latest `ca-certificates` package since I filed this ticket, so I'm closing the issue,
