### ISSUE TITLE
Text inside pie graph is too big 

### ISSUE THREAD

**Issue by ArcTanSusan** [18F/pulse#351]
I'm on the Chrome browser on normal zoom. The text "Participate in the DAP" is too big both on mobile and desktop views.

![pulse_landing_page](https://cloud.githubusercontent.com/assets/954858/12004427/360a6e02-ab0d-11e5-9cec-60fc94d04db2.png)

**Comment by onceuponatimeforever** [comment]
My attempt to resolve this bug: https://github.com/18F/pulse/pull/352

**Comment by CrazyPython** [comment]
Come on, 18F. You can do better. It's 2016!

**Comment by konklone** [comment]
@CrazyPython Please be respectful to the Watch-ers of our repositories and don't leave unconstructive comments like these. If you're using the project for something, always feel free to open an issue or leave a comment to move the project forward.

We did spend time and energy trying to reproduce the bug reporter's environment to catch size issues, but you can see from the thread here that we were not able to do so and the issue was closed: https://github.com/18F/pulse/issues/350 Closing this as well.
