### ISSUE TITLE
Sites that use SSL but use CloudFlare or similar services

### ISSUE THREAD

**Issue by WilliamFeely** [18F/pulse#359]
How about a field for your SSL list that lists government websites that appear HTTPS to the browser, but are proxied through CloudFlare or a similar service, as such services, especially CloudFlare, do not necessarily guarantee full end-to-end encryption from client to server?

**Comment by konklone** [comment]
I very much sympathize with wanting to detect this, but I don't know of any way to automatically detect this from the public internet -- and right now scans from the public internet are the basis for all of the HTTPS information on pulse.cio.gov.

**Comment by WilliamFeely** [comment]
One idea could be to scan the SSL certificates for something like sslxxxxxx.cloudflaressl.com as the subject, as for example fbi dot gov is proxied through CloudFlare and its certificate is issued to ssl331184.cloudflaressl.com
Makes me a bit apprehensive to use the tips dot fbi dot gov tipline, considering it may not be 100% confidential, especially if I want to report a criminal using CloudFlare's services.

**Comment by konklone** [comment]
Well, seeing a CloudFlare certificate isn't enough to prove that the connection is unencrypted between CloudFlare and the origin. CloudFlare supports strictly enforcing proxy->origin backend connections, there's just no way to tell from the outside whether that's in use or not. 

In addition, even if CloudFlare did something novel, like put an HTTP header that indicated which configuration a customer had, that would only apply to CloudFlare hosted sites. We would be missing the many other ways an agency might have an unencrypted backend connection (and you don't need a CDN in order to have one of those), and so we'd be giving people a false sense of security about the issue with non-CloudFlare services.

The issue you might face with potentially reporting a criminal using CloudFlare's services through a CloudFlare gateway is a separate issue, and also not one we can tackle. Many agencies use hosting services and CDNs operated by third parties, that if they wanted to could technically observe encrypted traffic, and there's nothing unique about CloudFlare in that regard.

I'm going to close the issue, as I don't think this is something we can effectively police with Pulse. However, I appreciate your concerns here (and I have my own personal reservations about CloudFlare's services unintentionally motivating people to obscure public auditability of unencrypted backend connections) -- thanks for opening the issue.
