### ISSUE TITLE
CBP is DHS part of Commerce?

### ISSUE THREAD

**Issue by rclar-in-dc** [18F/pulse#372]
Last I checked, CBP was part of DHS not Commerce, yet when I look them up on the analytics page they are shown as part of Commerce...

https://pulse.cio.gov/analytics/domains/

cbp.gov	Department of Commerce

**Comment by gbinal** [comment]
Thanks, @rclar-in-dc.  Looking into it.

**Comment by gbinal** [comment]
A belated follow up to this, but I've confirmed that this is stemming from original data source (the [.gov domain registry](https://github.com/GSA/data/blob/gh-pages/dotgov-domains/current-federal.csv#L143)).  There's a couple reasons this might be the case, including that Commerce operates a component that builds websites for other agencies.  

Regardless, since this is an issue coming from outside of the pulse project, I'm going to go ahead and close for now.
