### ISSUE TITLE
update your site certificate with a SAN of www.pulse.cio.gov

### ISSUE THREAD

**Issue by mbfel** [18F/pulse#422]
This link appears on page number 7 of the

ANNUAL REPORT TO CONGRESS:
FEDERAL INFORMATION SECURITY MODERNIZATION ACT
OFFICE OF MANAGEMENT AND BUDGET
March 18, 2016

in the section discussing the progress of agencies in adopting https.

Chrome reports the following error when navigating to that url:

Your connection is not private

Attackers might be trying to steal your information from www.pulse.cio.gov (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

I would think it a bit embarrassing to find that the site charged with monitoring the implementation of https has a certificate that gives an error when using the url in the above report. My guess is that they weren't supposed to prefix it with "www." but face it, it's hopeless to try to enforce that. Instead, get a certificate with that as a subject alternate name.

**Comment by konklone** [comment]
> I would think it a bit embarrassing to find that the site charged with monitoring the implementation of https has a certificate that gives an error when using the url in the above report. 

Yes, it is embarrassing that someone put an invalid link in a report to Congress -- we weren't aware of that, or certainly would have corrected it before it shipped. There was only even a DNS record for obscure and temporary operational reasons, we never officially supported it as a URL and never gave that URL out.

I'll add a SAN to the certificate, and have it redirect from www.pulse.cio.gov to pulse.cio.gov so that no one ends up accidentally bookmarking or sharing the www version. However, this is temporary -- we may drop the SAN, and the DNS record, down the line. I don't expect links buried in the Office of Management and Budget's annual FISMA reports to Congress to drive immense amounts of traffic.

For others who come across this thread, the [report is here](https://www.whitehouse.gov/sites/default/files/omb/assets/egov_docs/final_fy_2015_fisma_report_to_congress_03_18_2016.pdf) and the citation is on page 11 of the PDF:

![image](https://cloud.githubusercontent.com/assets/4592/14772536/78288f02-0a6d-11e6-970b-67e7fd072cc5.png)

**Comment by konklone** [comment]
This is done:

![image](https://cloud.githubusercontent.com/assets/4592/14772702/588088e2-0a6f-11e6-9547-b558009c9a21.png)
