### ISSUE TITLE
Are all gov URLs listed as the denominator for the % with analytics?

### ISSUE THREAD

**Issue by ErieMeyer** [18F/pulse#438]
Hi hi!

I was looking to see how many URLs that an agency owned, and saw that pulse thought Department of Education had 10 -- but was missing at least studentaid.gov -- 

![image](https://cloud.githubusercontent.com/assets/1626026/15578251/bf70cb58-232d-11e6-9e05-fb1d2cae66c1.png)

1. Should all gov URLs be the denominator?
2. I then looked at data.gov and couldn't find the data set of URLs cc @philipashlock
3. Would Pulse.cio.gov be up for considering hosting a list of all gov URLs? I think this would be a hilarious and awesome feature.

cc @carolaponce

**Comment by konklone** [comment]
Hey @ErieMeyer -- studentaid.gov redirects to studentaid.ed.gov. For the purposes of monitoring DAP compliance, Pulse automatically rules out "redirect domains" from being eligible. So ed.gov is monitored, but studentaid.gov is not.

Unfortunately, for domains that redirect to subdomains like that, Pulse has a gap in general, as there is no canonical list of .gov subdomains. Pulse is interested in integrating subdomains, but it's an open work item right now. If that's something you'd like to work on generally, feel free to reach out over email.

To answer your specific questions:

> Should all gov URLs be the denominator?

* Probably not, as some .gov URLs aren't used for websites (they're only used for email or other services), or they are redirect domains (e.g. for marketing purposes or for typo squatting). We try to make the best decision based on the thing we're measuring, without getting into the business of maintaining a list of special per-domain exceptions.

> I then looked at data.gov and couldn't find the data set of URLs cc @philipashlock

* The data.gov URL for the list of .gov domains is: https://catalog.data.gov/dataset/gov-domains-api-c9856. For a variety of reasons, a mirror of this data is also maintained at https://github.com/gsa/data.

> Would Pulse.cio.gov be up for considering hosting a list of all gov URLs? I think this would be a hilarious and awesome feature.

* Pulse links to the GitHub version of the data [on its FAQ](https://pulse.cio.gov/about/#what-domains-are-being-measured) (which at the time, was the only version of the data that included legislative and judicial domains, which are also included in the HTTPS section of Pulse).

I'm going to close this because I think this addresses everything, but please feel free to re-open if there are still Pulse action items to talk about here.

**Comment by konklone** [comment]
> We try to make the best decision based on the thing we're measuring, without getting into the business of maintaining a list of special per-domain exceptions.

I should clarify my comment here, as we do keep a list of [manually marked _ineligible_ DAP domains](https://github.com/18F/pulse/blob/master/data/ineligible/analytics.yml), which right now just has one domain. 

Unfortunately, it won't make sense to mark redirect domains manually as eligible, because they'll simply never be detected as compliant -- we detect DAP participation based on the DAP's [official list of participating domains](https://analytics.usa.gov/data/live/second-level-domains.csv), which pulls right from Google Analytics and will never have a record for studentaid.gov, only for studentaid.ed.gov.
