### ISSUE TITLE
outstanding issue, re: accessibility of datatables.js 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#464]

**Comment by nickbristow** [comment]
The issue we were trying to resolve was making the first cell in each row a `<th>` so it could properly use the `scope` attribute. 

The issue was the version we were using of `datatables responsive` plugin didn't support the `<th>` element. 

Updating the responsive plugin allowed us to use that element in the table. 

See: https://github.com/18F/pulse/pull/466

**Comment by gbinal** [comment]
This was addressed by #466.
