### ISSUE TITLE
Inconsistency in average errors and total errors by agency vs. by domain reporting in Pulse Accessibility

### ISSUE THREAD

**Issue by smarina04** [18F/pulse#506]
I just searched for all domains under Department of Health and Human Services, and:

1. Department of Health and Human Services: by domain, the sum of all errors is 832 (current data in staging).

2. Department of Health and Human Services, by agency. Average # of errors = 16. Total HTML errors - 16. All other errors - 0. 

Questions: 

1. Average of what? All errors by domain? If so, the number should be ~ 7, unless, this is a weighted average. Where is this 16 coming from and why do we have 0s everywhere else? Where is the disconnect?

2. Why don't we have a total errors by agency?

**Comment by gbinal** [comment]
Thanks, @smarina04.  We just noticed the first half this issue (it was correct as of a few weeks ago) and https://github.com/18F/pulse/issues/505 is tracking it.   

Question 1: `Average No. of Errors` should be `sum of the number of errors for the domains of an agency` divided by `number of domains an agency has (that are being scanned)`.   The rest of Question 1 is addressed by resolving #505.  

Question 2: This was a design choice by OGP since it would paint a worse picture for agencies with more domains.

**Comment by gbinal** [comment]
#505 should cover the outstanding aspects of this so I'm going to close for now in favor of it.  Feel free to reopen if there's something not covered by #505.
