### ISSUE TITLE
Remove bam.gov from DAP section

### ISSUE THREAD

**Issue by tdlowden** [18F/pulse#519]
as per @SamBronson, bam.gov redirects to cdc.gov, and therefore shouldn't be reflected in the DAP count.

**Comment by konklone** [comment]
@SamBronson How easy is it for you to make the redirect server-side (30X status code) instead of client-side (`<meta refresh`>)? We can add the exception for DAP here, but whether a domain is a "redirect domain" is something we use when measuring other aspects of domains, and we rely on server-side redirects for that detection.

**Comment by konklone** [comment]
I added this in https://github.com/18F/pulse/commit/5ffdd8d9e66c152d2e2cc785e616fd2c8cfa713a, which will make it to production in the near future.

**Comment by SamBronson** [comment]
@konklone This is a CDC managed site, so it's out of my hands, but I will pass along that sound suggestion to our CDC Digital Council Rep.  I was acting selfishly in this case to boost our DAP compliance score.

**Comment by konklone** [comment]
Much obliged!

**Comment by konklone** [comment]
@SamBronson As something you can send to the CDC rep of an example of how Pulse looks for server-side redirects, this is the [GSA/OMB guidance for HTTPS](https://https.cio.gov/guide/#this-site-redirects-users-to-https----why-is-pulse-saying-it-doesn't-enforce-https%3f) that emphasizes the same thing.

**Comment by SamBronson** [comment]
Perfect; thanks.
