### ISSUE TITLE
How to add "SSL Labs Grade" rating "A" for vets.gov?

### ISSUE THREAD

**Issue by joduinn** [18F/pulse#533]
(Unsure if this is right mechanism for asking question - if not, please close with details or pointer to docs - and sorry for the noise)

Looking at https://pulse.cio.gov/https/domains/#q=Department%20of%20Veterans%20Affairs, I see that some VA owned domains have a rating from QualysSSLLabs, while some domains do not. Specifically, I noticed that vets.gov had no SSL Labs Grade rating posted. 

I took the URL used for nrd.gov, and modified it ( https://www.ssllabs.com/ssltest/analyze.html?d=www.vets.gov) to run a scan of vets.gov and happily got a rating of "A". However, this rating does not show up on https://pulse.cio.gov/https/domains/#q=Department%20of%20Veterans%20Affairs, even after a couple of retries, and waiting for possible overnight refreshes. 

I'm obviously missing some step, hence the question: how to get a "SSL Labs Grade" rating posted for vets.gov on https://pulse.cio.gov/https/domains/#q=Department%20of%20Veterans%20Affairs?

**Comment by konklone** [comment]
@joduinn Well, it is scanned. This is the latest result from SSL Labs for vets.gov:

https://s3.amazonaws.com/pulse.cio.gov/live/cache/tls/vets.gov.json

The error is `Unable to resolve domain name`. That's from SSL Labs' perspective, not our server's. (Our server sees `vets.gov` just fine, and [can reach it directly by HTTP](https://s3.amazonaws.com/pulse.cio.gov/live/cache/pshtt/vets.gov.json).) It looks like that error has been consistent for weeks now. I am not sure why this happening, especially since, as you pointed out, https://www.ssllabs.com/ssltest/analyze.html?d=vets.gov works fine. 

(Note that SSL Labs now doesn't auto-detect whether a site uses `www` or not, so the result for `vets.gov` may be different than for `www.vets.gov`. We're checking `vets.gov`, because the canonical URL is `https://vets.gov`.)

When I run `ssllabs-scan` locally, and when I run it on our production server as a one-off task, I get an `A` response. When I check what SSL Labs scans in our last production scan got the same error, I get 56 domains, including `tva.gov`, `secretservice.gov`, and more. These also appear to be consistent, week-to-week.

I am glad you pointed this out, because I hadn't noticed this happening, but I am not sure what causes these issues or what to do about it. I would guess that SSL Labs shows stress under repeated scans, but I don't think the results would be so consistent week-to-week if that were the case. And in any case, we don't even touch their rate limit, limiting our SSL Labs scans to 1 at a time.

You've got me stumped. I think this is a bug with SSL Labs.

**Comment by anand-bhat** [comment]
FWIW, I'd reported https://github.com/ssllabs/ssllabs-scan/issues/376 a few weeks ago for the same issue for a different domain. For about a week between the time I became aware of the domain and I created the issue, the domain was accessible from my browser and scannable via other online services but I could not scan it using the SSL Labs site or the API.

**Comment by tdelmas** [comment]
http://dnssec-debugger.verisignlabs.com/vets.gov reports broken DNSSEC

**Comment by joduinn** [comment]
> @joduinn Well, it is scanned. This is the latest result from SSL Labs for vets.gov:
https://s3.amazonaws.com/pulse.cio.gov/live/cache/tls/vets.gov.json

Hi @konklone , @tdelmas : Good to know vets.gov is actually being scanned - and thanks for the link to the json file. Thats v.helpful and also interesting on many levels. 
1) the json file mentions "port": 443, "protocol": "HTTP" which seems odd to me. Shouldn't that be port 80 or protocol HTTPS? 
2) our nginx configs redirect all HTTP traffic to HTTPS, and all vets.gov traffic to www.vets.gov (which matches the cert we use). I cant imagine we're the only ones doing this, but I wonder if this is confusing the SSLlabs code generating the json file?
3) the DNSSEC errors are news to me - I'll investigate with our network ops folks.

**Comment by konklone** [comment]
I don't think (1) or (2) are issues, for the reasons you suggested -- that's an extremely common configuration, and shouldn't cause an issue. I suspect it's the DNSSEC errors. My understanding is that the .gov registry has an arrangement with Google where Google DNS hard-fails on .gov domains, if there's DNSSEC entries to validate against. I wasn't aware that SSL Labs used Google DNS for resolution, which would explain it.

I am still confused as to why I *can* get vets.gov and www.vets.gov to work with ssllabs-scan when I do one-off executions, and when I access it in the browser myself. But it's extremely consistent during our weekly scans, and I know that DNSSEC misconfiguration will cause real issues with at least Google DNS and Comcast DNS users, so this is worth investigating.

**Comment by tdelmas** [comment]
@joduinn @konklone Note that ssllabs only check the www if it resolve to another IP than the main domain: https://github.com/ssllabs/ssllabs-scan/issues/187

**Comment by konklone** [comment]
@tdelmas I believe that is no longer the case - in 2016, SSL Labs changed its behavior to only check the explicit hostname it's given. So it will give different results if given `example.com` and `www.example.com`. Pulse is changing its behavior, as of the next scan, to give SSL Labs the `www` hostname if we detected it to be the canonical version of the site. However, this change won't affect vets.gov, as we already detect is canonical URL to be `https://vets.gov`.

**Comment by joduinn** [comment]
@tdelmas @konklone No news yet, but folks here working on the DNSSEC errors. Will update here when I have news.

**Comment by joduinn** [comment]
@tdelmas @konklone 

Got news late Friday from internet about some changes done internally on DNS at VA as a result of this discussion. Over the weekend I then reran http://dnssec-debugger.verisignlabs.com/vets.gov which now reports *no* DNSSEC errors!! With this fixed, I then re-ran https://www.ssllabs.com/ssltest/analyze.html?d=www.vets.gov and then confirmed pulse is displaying the "A"!! 

In end effect, this was not a problem with pulse.cio.gov, only that pulse was showing the first symptom of the root problem. 

Happily closing - with special thanks to @tdelmas for the pointer to the http://dnssec-debugger.verisignlabs.com/vets.gov which was crucial to finding the root cause.


@konklone I note above that you said you saw the same errors with ~56 other government websites. Unknown if they are hitting the same error, but happy to introduce them to the people I worked with in VA if that will help. If there's another bug tracking fixing the other ~56 websites, please link to here for context.

**Comment by konklone** [comment]
Awesome! I am glad this worked out.

cc-ing @h-m-f-t in case he or his team are interested in pinging the other agencies about potential DNSSEC configuration errors.

**Comment by konklone** [comment]
Awesome! I am glad this worked out.

cc-ing @h-m-f-t in case he or his team are interested in pinging the other agencies about potential DNSSEC configuration errors.
