### ISSUE TITLE
HUD domains in DAP section redirecting

### ISSUE THREAD

**Issue by tdlowden** [18F/pulse#649]
The DAP POC for HUD responded to an inquiry about HUD domains not appearing as DAP-implemented with the following:

![screen shot 2017-02-07 at 9 29 28 am](https://cloud.githubusercontent.com/assets/6556888/22695218/fa9a02a8-ed17-11e6-86bb-31d64e944512.png)

**Comment by konklone** [comment]
I haven't looked into each of these, but hud.gov uses a `<meta>` tag and JS code (both with a plain http: URL) to do the redirect instead of a server-side redirect, and www.nls.gov appears to do the same thing (but behind a busted certificate).

@tdlowden Want to CC me and pulse@cio.gov onto the thread with the HUD POC so I can relay the details to them for them to address?

If homesales.gov is owned by USDA, they need to put in a request to registrar@dotgov.gov to have that changed in the dotgov database, as Pulse relies on their underlying data for the determination.

**Comment by tdlowden** [comment]
Done. Thx @konklone

**Comment by gbinal** [comment]
These URLs were added to the [ineligible list](https://github.com/18F/pulse/blob/9c14f98d2d4871f5d3c153e0b90bd3823ddde4da/data/ineligible/analytics.yml), so is no longer showing in the report.
