### ISSUE TITLE
Review as a potential resource for 3rd party services

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#757]
https://github.com/paulirish/third-party-decode

**Comment by konklone** [comment]
I'm also talking with the guy behind this, which seems outstanding:

https://github.com/timlib/webXray/blob/master/webxray/resources/org_domains/org_domains.json

Bear in mind it's part of a GPLv3 repo, though I think that since these are facts and not code, it wouldn't stop us from using it in a non-GPL product in at least some other transformed schema/form.
