### ISSUE TITLE
Pulse does not include legislative agencies

### ISSUE THREAD

**Issue by jcyph3r** [18F/pulse#811]
Although the CSV file on github ostensibly used for the HTTPS scanning does include legislative branch agencies, those agencies seem to be omitted from the scan/status results page.

**Comment by freegovinfo** [comment]
Has this been updated? We're planning to use data from pulse for the [2020 End of Term crawl ](http://eotarchive.cdlib.org) so it'd be very helpful if it included legislative branch agencies.

**Comment by gbinal** [comment]
The pulse.cio.gov website has been decommissioned and set to redirect to digitaldashboard.gov.  

@freegovinfo and @jcyph3r, if you're interested in following up more on this, please reach out to site-scanning@gsa.gov, where a similar effort has begun and would be interested in understanding your use cases.  More background [here](https://github.com/18F/site-scanning-documentation).

In the meantime, closing this issue since the program has been wound down
